### PR TITLE
Fix crash when enabling OpenGL on macOS

### PR DESCRIPTION
**Pull request by pd95**
On current macOS systems SDL2 is required. To make "OpenGL" rendering available, the `host_screen_opengl.cpp` had to be modified to properly select the correct SDL render driver. There are multiple available and the default is "metal".

The fixed implementation loops over all render drivers and selects the first starting with "opengl" in his name.
This implementation has been successfully tested with SDL 2.24.2 and 2.26.2.

But on an Mac with Apple Silicon there is no measurable difference between the default Metal based renderer and the OpenGL renderer.

### CODE REVIEW

**Comment by th-otto** [comment]
Applied now, with a few changes:

- i used our own bug() function for debug printf instead of SDL_LogWarn()
- when creating the renderer fails, it falls back to the same code as when screen creation, ie, disabling opengl.enabled and using HostScreen::setVideoMode()

Hope thats ok.

I also wonder why that  fixes the crash. Previously, it used SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED). Did that create a different renderer than the one you get now?
Only difference for me seems to be that previously, a renderer might have created multiple times. I'm not sure whether that is needed when bpp changes (ie when switching from the info screen to the real window), but for now it seems to work.

**Comment by pd95** [comment]
On macOS (and iOS) SDL has multiple accelerated renderers. The previous solution with `SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED)` opened the Metal renderer and therefore OpenGL was not load. The dynamic library was not load and therefore it crashed.

**Comment by pd95** [comment]
It seems that we still have an issue in the current implementation when the window is resized. I think `SDL_GetWindowDisplayMode` is not returning the proper size of the window... I have to investigate.

**Comment by pd95** [comment]
Closing PR as it has already merged into main.

**Pull request closed without merging**
