### PR TITLE
Reuse icon file and install normal/JIT/MMU files conditionally

### PR DESCRIPTION
**Pull request by chewi**
Otherwise you end up with broken desktop entries. Reusing the icon file is not just tidier but also avoids awkward Automake logic.

To be more specific, putting `if USE_JIT` in the middle of the `for` loop doesn't work because of the backslashes.

### CODE REVIEW

**Comment by th-otto** [comment]
I don't see any USE_JIT there in the original version. I can't see anything wrong in the desktop files, they will point to aranym-jit.png etc. which is created as symlink to the normal version.

**Comment by chewi** [comment]
Sorry, I should have been clearer. You're assuming that all the variants will be built but the user may not run configure the necessary 3 times. If you only enable PMMU, for example, then the regular desktop file and the JIT desktop file will be broken.

You were creating duplicates of the .png files under /usr/share/icons and I tried to keep it that way by doing the following but it doesn't work.

```
        for s in 32 48; do \
                $(mkinstalldirs) "${DESTDIR}${datadir}/icons/hicolor/$${s}x$${s}/apps/"; \
if USE_JIT
                $(INSTALL_DATA) $(top_srcdir)/contrib/icon-$${s}.png "${DESTDIR}${datadir}/icons/hicolor/$${s}x$${s}/apps/aranym-jit.png"; \
else
if FULLMMU
                $(INSTALL_DATA) $(top_srcdir)/contrib/icon-$${s}.png "${DESTDIR}${datadir}/icons/hicolor/$${s}x$${s}/apps/aranym-mmu.png"; \
else
                $(INSTALL_DATA) $(top_srcdir)/contrib/icon-$${s}.png "${DESTDIR}${datadir}/icons/hicolor/$${s}x$${s}/apps/aranym.png"; \
endif
endif
        done
```

I don't know why the Cygwin build has failed above. Cygwin supports multiple Automake versions including 1.16, which I am using, but maybe it defaults to an older one.

I broke the AppImage build slightly so I'll try to fix that now.

**Comment by chewi** [comment]
Okay, I see Appveyor is failing because of this in `.appveyor/build.sh`.

```
make -f Makefile.am top_srcdir=. "$datefile"
```

That's cheating. :wink: Automake files are not guaranteed to be parseable by Make. I've worked around it by moving the code that generates version_date.h into version_date.sh.

**Comment by chewi** [comment]
> Especially, if you look at the whole build process, your attempt does not work. There is only one package, with all three binaries, and only the executable is moved around, so all possible desktop files and icons have to be installed.

On this point, I have fixed the AppImage build by doing `make install-strip` each time. It only worked before because you did the "normal" build last. If it had been in a different order then it would have been overwritten by the other builds. Now it will work in any order.

**Comment by th-otto** [comment]
AppImage is different, because by design it can only contain only a single Application. 

>it only worked before because you did the "normal" build last

No, there are three AppImage packages. 

>Admittedly this has been a bit more involved than I anticipated!

Sorry, but i don't see anything improved. If you only build a single version locally, and install that, well yes, than you have two other desktop files which reference uninstalled executables. But thats about all. But i actually never have done that (make install), this is only meant to make to build a distribution archive, and run by another script. Locally, i just use the version i compiled, without installing it.

**Comment by chewi** [comment]
It's because I'm an Amiga guy, isn't it? :stuck_out_tongue: 

You may build and use it that way but the `./configure && make && make install` mantra is still pretty ingrained within the community and I was just trying to make this common approach a little less broken. My Gentoo package was only going to let you build one of the three types as I thought it unlikely that anyone would need more than one. I'll adjust it to build more than one but I'll still need to fix this up for the architectures that don't support JIT. It's a shame because the build system otherwise works really well, which is often not a given, so credit to you there.

**Comment by th-otto** [comment]
>It's because I'm an Amiga guy, isn't it?

lol, you are? No, surely not. That times are over.

>I thought it unlikely that anyone would need more than one

The JIT version is about 10x faster than the normal one, so most of the time users prefer that. But it still may have some bugs here and there. The MMU version is needed for MiNT + Memory Protection, or to run the linux-68k kernel. So there is a reason for all of them.

>I'll still need to fix this up for the architectures that don't support JIT

Are there still any systems out there without x86 or arm? ;)

**Pull request closed without merging**
