### PR TITLE
Travis CI optimized

### PR DESCRIPTION
**Pull request by sagudev**
- Lower build times
- Building `arm64` natively without QEMU
- Fixed snaps pushing for non-amd64 platforms
- Disable running armhf on PR (for faster PR state)
- Fixed snaps stage-packages

### CODE REVIEW

**Comment by th-otto** [comment]
I've merged that manually, doing some minor formatting changes only.

**Comment by sagudev** [comment]
Logs says:
```
Unexpected error when obtaining your account information.

Login failed.
```
Maybe recheck `SNAP_TOKEN`

**Comment by th-otto** [comment]
??? where do you see that log? In my view, the build (and also deploy) succeeded.

**Comment by sagudev** [comment]
Here is in [log for amd64.](https://travis-ci.org/github/aranym/aranym/jobs/710795911#L3477)
You can also check snapcraft store. Last upload date is may 2019, so probably it is broken from then.

**Comment by th-otto** [comment]
Ah ok. I guess @joysfera has to look after that.

**Comment by th-otto** [comment]
Argl. Please use a new PR for further changes, the previous commits have already been applied.

**Comment by joysfera** [comment]
> Ah ok. I guess @joysfera has to look after that.

I feel like we were using some kind of a test account for the snaps and we need to "upgrade" to the full snap account that I've got credentials for long(ish) time ago.

**Comment by sagudev** [comment]
We are still getting same error in latest build. 
https://travis-ci.org/github/aranym/aranym/jobs/723305940#L2504

**Pull request closed without merging**
