### PR TITLE
Add armhf builds

### PR DESCRIPTION
**Pull request by sagudev**
Added armhf builds. See #12 

**BEFORE MERGE CREATE `temp` PACKAGE IN ARANYM BINTRAY**

### CODE REVIEW

**Comment by th-otto** [comment]
Many thanks! Pushed now. (with a few small fixes for missing line endings at the end of files)

Build took ~34min.

**Comment by th-otto** [comment]
Just noticed: the tar files are named *xenial* (because that is the used build environment on travis). I think it would be clearer to use rpi3 or something like that instead.

**Comment by sagudev** [comment]
I was looking at that too, but I kept naming like in 64 bit builds.

**Comment by th-otto** [comment]
Yes, but the other builds are using a native compiler, the the archives are for the system they are build on, unlike the arm builds. Also, it would conflict with the linux version, if we decide one day to use xenial there, too (currently it is still using trusty). But it should be easy to change that, should it be necessary.

**Comment by sagudev** [comment]
So you recommend to write Raspbian. Because its compiled on Raspbian.

**Pull request closed without merging**
