### PR TITLE
Added snap support

### PR DESCRIPTION
**Pull request by sagudev**
See #12 
For successful build see: https://travis-ci.org/sagudev/aranym/builds/507500817
For snaps go to: https://snapcraft.io/sagudev-aranym/releases

TODO before merging:
- [ ] Create snap on https://snapcraft.io/ called aranym
- [ ] Create Snapcraft token with `snapcraft export-login --snaps aranym -`
- [ ] Add `SNAP_TOKEN=your_snapcraft_token_here` to Travis like Bintray api key.
- [ ] Rerun Travis build

**Aranym 64bit is now build in Xenial**

### CODE REVIEW

**Comment by sagudev** [comment]
Now PR has new fix for #17. Well we still need to repair makefile, but in part of building you have ~4min to create new tag.

**Comment by sagudev** [comment]
Latest successful build here: https://travis-ci.org/sagudev/aranym/builds/520819919

**Comment by th-otto** [comment]
I think your "case $CPU_TYPE" in snap_create in deploy.sh is wrong, CPU_TYPE is set in setup_env.sh to x86_64|i386|arm|armhf

**Comment by sagudev** [comment]
Yes and if it is containing 64 it build amd64 and if it is arm it build armhf. Where is the problem?

**Comment by th-otto** [comment]
The problem is that CPU_TYPE is "x86_64", not "64". And form arm it may also be "armhf", not "arm"

**Comment by sagudev** [comment]
For arm I am already repair locally and for 64 I will repair too.
PS I's nothing. I did mistake in push.

**Comment by sagudev** [comment]
Done.

**Comment by sagudev** [comment]
Link to new build: https://travis-ci.org/sagudev/aranym/builds/537807815

**Comment by joysfera** [comment]
@sagudev SNAP_TOKEN added to Travis. Don't ask why it took so long.

**Pull request merged**
