### PR TITLE
JIT back in snap

### PR DESCRIPTION
**Pull request by sagudev**
Fix for #59 and aliases so now you can use these commands from snap:
```bash
> aranym

> aranym-mmu

> aranym-jit

> aratapif
```

### CODE REVIEW

**Comment by sagudev** [comment]
For aliases we need to request it like https://forum.snapcraft.io/t/request-alias-for-lagoon-cli-snap/15510

**Comment by sagudev** [comment]
@joysfera any progress yet?

**Comment by sagudev** [comment]
ping @th-otto

**Comment by joysfera** [comment]
I got everything needed from Ubuntu to create final snap (long time ago).

**Comment by th-otto** [comment]
So do we need this patch at all?

**Comment by sagudev** [comment]
Yes, because you still need to have aliases in snapcraft file. And this PR also have fix for #59.

**Comment by th-otto** [comment]
Ok, and sorry for the delay.

**Comment by sagudev** [comment]
I have also been working on refactoring emu part of Aranym for faster build times, so expect new PR soon.

**Comment by th-otto** [comment]
On my machine it builds in ~18s, that is fast enough for me ;) I don't really care how long it takes on travis CI

**Comment by sagudev** [comment]
The problem is consistency. For example [latest build failed](https://travis-ci.org/github/aranym/aranym/builds/707904828) but when I run it in [my fork (same commit)](https://travis-ci.com/github/sagudev/aranym) there was no error. Faster builds is just bonus.

**Pull request merged**
