### PR TITLE
Revert "Reorganize tos patches for 4.04"

### PR DESCRIPTION
**Pull request by pd95**
This reverts commit 70c9dc44da2b2e2400ea9626937420b1a6f08038.

### CODE REVIEW

**Comment by uweseimet** [comment]
I can confirm that after applying this patch the related issue is resolved, i.e. I can boot again from my image with TOS 4.04.

**Comment by joysfera** [comment]
I hear you. I hope to find some spare time to have a look at this sometime soon.

**Comment by joysfera** [comment]
Debugged and fixed properly in https://github.com/aranym/aranym/commit/989674df504aafd02f28339e7ffe96a26da504a7 so this PR is no longer needed.

**Comment by th-otto** [comment]
Thanks for looking into it. Looking at your your fix, there seems to be 3 things that you fixed:

- in my patch a nop'ed out movec d0,cacr was missing compared to the original patch routines. Dunno why i left that out (maybe just overlooked it), but since that code is in the coldboot routine only, i guess it does not affect this bug
- The new rom CRC was missing. Not even sure whether the new values are correct, but since the code that checks it is disabled by the patches, not very important.
- I introduced a new patch in the IDE timeout routine. I guess that code was causing the bug.

I still don't understand why this patch in the IDE routine caused problems. In pseudo-code, the original routine would be something like:

int iderdy(int unit);
*(0xfff00019) = unit << 4;
timeout = hz200 + 1000;
while (*(0xfff00039) != 0x50)
{
   if (hz200 >= timeout)
      return 0;
}
return 1;

Or in other words, it selects the unit, then waits for 0xfff00039 to become 0x50. What my patch did was to remove the timeout check and immediately return with an error, on the assumption that, in the emulator, the unit is either ready or not, but will not change that state after some timeout.

What did i miss here?

**Pull request closed without merging**
